#!/bin/bash

# Rip playlist to dir and convert to mp3

# PLAYLIST="$1"                                           ;
# yt-dlp -x $PLAYLIST                                     ;

# Convert files to mp3
for i in *.opus; do ffmpeg -i "$i" "${i%.*}.mp3"; done  ;
for i in *.m4a; do ffmpeg -i "$i" "${i%.*}.mp3"; done   ;

# Organizing Files
mkdir opus
mkdir mp3
mv *.mp3 ./mp3
mv *.opus ./opus
