#!/bin/bash

# Script to download a section of a video. It will default to best quality.
# Example: vcut <url> <start time> <end time>

VIDEO=$1                                                                           ;
START=$2                                                                           ;
END=$3                                                                             ;

yt-dlp $VIDEO --downloader ffmpeg --downloader-args "ffmpeg_i:-ss $START -to $END" ;
