#!/bin/bash
# Script to download a video file then trim it.

# Requires
# python3 -m pip install -U yt-dlp
# sudo apt install ffmpeg

# Example: vcut https://www.youtube.com/watch?v=dQw4w9WgXcQ 0:00 0:05

FILE="$1"
START="$2"
END="$3"
TMP="/tmp/vcut"
OUT="~/output"

# Making directories
mkdir $TMP
mkdir $OUT
cd $TMP

# Using yt-dlp to download the file
yt-dlp $FILE

# Using ffmpeg to trim the video and remux to .webm
ffmpeg -ss $START -to $END -i ./* -codec copy output_$RANDOM.webm

# Cleanup
mv $TMP/* ~/output
