#!/usr/bin/python3
import os
import sys
import random

"""
You need to install ffmpeg with your package installer and yt-dlp to use this
    sudo apt install ffmpeg
    python3 -m pip install -U yt-dlp
"""

output_dir = '~/output'
tmp_dir = '/tmp/ffmpeg'
clip_name = 'clip' + str(random.randrange(69,420)) + '.webm' # Switch this to mp4 if you need a better container format
local_clip = ''

print("\n # Download and Trim: video-cutter https://youtube.com/example 00:00 00:10")
print("\n # Just trim a video: video-cutter -ss ./example 00:00 00:10\n")

if len(sys.argv) == 4:
    arg1, arg2, arg3 = sys.argv[1], sys.argv[2], sys.argv[3]
    link, start_time, end_time = arg1, arg2, arg3
    print (f'Video url -  {arg1} \nStart time -  {arg2}\nEnd time -  {arg3}')
    # Making tmp and output directories
    if os.path.exists(tmp_dir) or os.path.exists(output_dir) is False:
        os.system(f'mkdir {tmp_dir}')
        os.system(f'mkdir {output_dir}')
    os.chdir(tmp_dir)
    os.system(f"yt-dlp --no-playlist {link}") # Downloading the video 

elif len(sys.argv) == 5:
    arg1, arg2, arg3, arg4 = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]
    local_clip, start_time, end_time = arg2, arg3, arg4
    os.system(f'ffmpeg -ss {start_time} -to {end_time} -i {local_clip} -codec copy {clip_name}')
    exit()

os.system(f'ffmpeg -ss {start_time}  -to  {end_time} -i {tmp_dir}/*  {clip_name}') # Cutting the video

 # Cleanup
os.system(f'mv {tmp_dir}/* {output_dir}')
